global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'some-metrics'
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:1234']
